<!-- Footer -->
<div id="footer">
  <!-- Icons -->
  <ul class="icons">
  	<li><a href="#" class="icon fa-github"><span class="label">GitHub</span></a></li>
  </ul>
  <!-- Copyright -->
  <div class="copyright">
  	<ul class="menu">
  		<li>Project funded by</li>
  		<li><a href="http://www.salford.ac.uk/">The University of Salford</a></li>
  		<li><a href="http://www.vicon.com/">Vicon</a></li>		
  	</ul>
  </div>
</div>