<!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/jquery.dropotron.min.js"></script>
    <script src="assets/js/skel.min.js"></script>
    <script src="assets/js/util.js"></script>
    <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
    <script src="assets/js/main.js"></script>

<!-- Header -->
    <div id="header">

        <!-- Logo -->
            <h1><a href="index.html" id="logo">Python  <em>Conventional Gait Model</em></a></h1>

        <!-- Nav -->
            <nav id="nav">
                <ul class=nav>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="Team.html">Team</a></li>
                    </ul>
            </nav>

    </div>


<!-- Banner -->
    <section id="banner">
            <img src="images/pyCGM2logo.png" /><br/>
        <header>
            <h2><em>An Open Source package of the Conventional Gait Model</em></h2>
            <a href="#" class="button">Learn More about the CGM</a>
        </header>
    </section>

<div id="page-wrapper">
